# Generated by Django 6.0.6 on 2026-06-08 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=20)),
                ('extra_phone', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('education_type', models.CharField(max_length=50)),
                ('education_form', models.CharField(max_length=50)),
                ('education_language', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Qabul arizasi',
                'verbose_name_plural': 'Qabul arizalari',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('message', models.TextField(max_length=1200)),
            ],
            options={
                'verbose_name': 'Yuborilgan xabar',
                'verbose_name_plural': 'Yuborilgan xabarlar',
            },
        ),
    ]
